### ISSUE TITLE
Treat AA:BB input as mm:ss not hh:mm in length

### ISSUE THREAD

**Issue by UVJkiNTQ** [NeoCoderMatrix86/AudioCuesheetEditor#209]
**Is your feature request related to a problem? Please describe.**
I often use the length cell to input the time stamp. The length is usually decribed in mm:ss as a track will seldom last a hour.
**Describe the solution you'd like**
Reconize 2:14 as 2 minutes and 14 seconds.

**Comment by NeoCoderMatrix86** [comment]
I understand your point, I also use this the same way. I'll try to find a solution and when to include this into a release.

**Comment by NeoCoderMatrix86** [comment]
@UVJkiNTQ This feature is now available. You can use a customized timespan format of 

> (?'TimeSpanFormat.Minutes'\d{1,})[:](?'TimeSpanFormat.Seconds'\d{1,})
