### ISSUE TITLE
Add "Select All" to tracks table

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [NeoCoderMatrix86/AudioCuesheetEditor#252]
Add a "select all" column to tracks table

**Comment by etroo44** [comment]
Can I work on this? But I need more information on what exactly "select all" should do.

**Comment by NeoCoderMatrix86** [comment]
> Can I work on this? But I need more information on what exactly "select all" should do.

Yes, sure you can. I would be happy for some help of others :). Well, basically here is a screenshot how it should work:

![grafik](https://user-images.githubusercontent.com/40752681/195264647-4e1355ae-5c73-45d9-bb3d-5ddc139839a4.png)

Selecting tracks is currently possible, but you can not select all tracks at once (or deselect all at once). So the basic idea is to have a checkbox in the header to select/deselect all.

Just some thoughts for planning: The next release should go online at the next month. If you are able to provide a pull request until then, I would include it into the release.

**Comment by NeoCoderMatrix86** [comment]
No problem, you can start :). If you need some help, just ask :).
