### ISSUE TITLE
Bug in options/common settings

### ISSUE THREAD

**Issue by JedrzejMakuch** [NeoCoderMatrix86/AudioCuesheetEditor#306]
**Describe the bug**
Customized timespan format input, when u click and chose any placeholder, then chose it again, in input it makes another input, and there is few placeholders in one input.

**Exception details (if possible)**
1. Open developer tools (usually found by pressing F12)
2. Open tab console.
3. Copy contents and paste here.

**To Reproduce**
1. Go to Options
2. Click on placeholder
3. Chose another placeholder
4. Error occurs in input

**Expected behavior**

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/109082644/228022062-0acfa6d2-c80e-40da-9336-5d9db44a925d.png)

**Comment by NeoCoderMatrix86** [comment]
Hello,
thanks for the contribution and reporting the bug. I'm currently not understanding, what is reacting wrong?!
The idea behind the customized timespan format is that you can edit how input to timespan fields are interpreted. Therefore you can enter multiple placeholders like "(?'TimeSpanFormat.Minutes'\d{1,})[:](?'TimeSpanFormat.Seconds'\d{1,})" which means that a format like "12:34" is interpreted like 12 minutes, 34 seconds. Could you make clear, where a bug is?

**Comment by NeoCoderMatrix86** [comment]
@JedrzejMakuch Is it possible for you to make a comment, where I can help you? :)
