### ISSUE TITLE
Import view has unexpected file upload button

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [NeoCoderMatrix86/AudioCuesheetEditor#348]
![grafik](https://github.com/NeoCoderMatrix86/AudioCuesheetEditor/assets/40752681/55a726e9-fdfb-4e1a-a1f6-a1d0e0e1ae51)

**Comment by cbtk15** [comment]
Hi @NeoCoderMatrix86, I'm quite new to contributing but I thought this would be a good one to try and solve. Please can I be assigned to this issue? :)

**Comment by NeoCoderMatrix86** [comment]
@cbtk15 Thanks for your help. You are welcome to support this project and have a try in resolving this issue.
To the details: I think this might be a css related issue, since we use blazorise for ui components. But I also would have to look around, where the bug is ;).

**Comment by cbtk15** [comment]
Thank you, @NeoCoderMatrix86 ! Really appreciate it :) I've fixed the bug! I'll go over the commits and do a pr, if that's okay :)
