### ISSUE TITLE
Track validation of begin/end is failing

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [NeoCoderMatrix86/AudioCuesheetEditor#349]
Validation of the fields begin and end of a track is wrong, since you can enter an end that is before the begin. The track is just invalid because of the empty length.

![grafik](https://github.com/NeoCoderMatrix86/AudioCuesheetEditor/assets/40752681/e1b7f5a6-4f88-4c53-859b-815e86f8653f)

**Comment by agusaar** [comment]
I would like to work on it

**Comment by NeoCoderMatrix86** [comment]
@agusaar:
Thank you for your interest, you are welcome to take this issue. I'll write down just a few thoughts, hoping it makes you easier to get onboard.
Basically I would assume that a track begin is equal or less to its end and equal or greater to zero. End should be greater or equal to Begin.
The validation is done inside each entity, so the Track entity has a Validate() method, where this can be achieved.
Do not forget to add a unit tests to check the begin and end validation (there are examples inside the unit tests).
So, I hope you can start, if you have a question, just ask ;).

**Comment by NeoCoderMatrix86** [comment]
@agusaar: Any progress here?
